config/routes.rb
Abc74st20::Application.routes.draw do
  root :to => "interface#dasboard"
  get "activations" => "interface#activations"

  get "portins" => "interface#portins"

  get "reups" => "interface#reups"
  resources :admins

  resources :reups

  resources :simple_portins

  resources :simple_activations

  resources :ultra_reups

  resources :ultra_portins

  resources :ultra_activations

  resources :wallets

  resources :ptel_reups

  resources :ptel_portins

  resources :ptel_activations

  

end

app/models/ultra_reup.rb
class UltraReup < ActiveRecord::Base
	belongs_to :admin
end

app/controllers/ultra_reups_controller.rb
class UltraReupsController < ApplicationController
  before_action :set_ultra_reup, only: [:show, :edit, :update, :destroy]

  # GET /ultra_reups
  # GET /ultra_reups.json
  def index
    @ultra_reups = UltraReup.all
  end

  # GET /ultra_reups/1
  # GET /ultra_reups/1.json
  def show
  end

  # GET /ultra_reups/new
  def new
    @ultra_reup = UltraReup.new
  end

  # GET /ultra_reups/1/edit
  def edit
  end

  # POST /ultra_reups
  # POST /ultra_reups.json
  def create
    @ultra_reup = UltraReup.new(ultra_reup_params)

    respond_to do |format|
      if @ultra_reup.save
        format.html { redirect_to @ultra_reup, notice: 'Ultra reup was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ultra_reup }
      else
        format.html { render action: 'new' }
        format.json { render json: @ultra_reup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ultra_reups/1
  # PATCH/PUT /ultra_reups/1.json
  def update
    respond_to do |format|
      if @ultra_reup.update(ultra_reup_params)
        format.html { redirect_to @ultra_reup, notice: 'Ultra reup was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ultra_reup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ultra_reups/1
  # DELETE /ultra_reups/1.json
  def destroy
    @ultra_reup.destroy
    respond_to do |format|
      format.html { redirect_to ultra_reups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ultra_reup
      @ultra_reup = UltraReup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ultra_reup_params
      params.require(:ultra_reup).permit(:phone_number, :nineteen_plan, :twentynine_plan, :thirtynine_plan, :fourtynine_plan, :fiftynine_plan, :other_amount, :amount, :admin_id, :wallet_id)
    end
end

app/helpers/ultra_reups_helper.rb
module UltraReupsHelper
end

app/views/ultra_reups/_form.html.erb
<%= form_for(@ultra_reup) do |f| %>
  <% if @ultra_reup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ultra_reup.errors.count, "error") %> prohibited this ultra_reup from being saved:</h2>

      <ul>
      <% @ultra_reup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :nineteen_plan %><br>
    <%= f.check_box :nineteen_plan %>
  </div>
  <div class="field">
    <%= f.label :twentynine_plan %><br>
    <%= f.check_box :twentynine_plan %>
  </div>
  <div class="field">
    <%= f.label :thirtynine_plan %><br>
    <%= f.check_box :thirtynine_plan %>
  </div>
  <div class="field">
    <%= f.label :fourtynine_plan %><br>
    <%= f.check_box :fourtynine_plan %>
  </div>
  <div class="field">
    <%= f.label :fiftynine_plan %><br>
    <%= f.check_box :fiftynine_plan %>
  </div>
  <div class="field">
    <%= f.label :other_amount %><br>
    <%= f.check_box :other_amount %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :admin_id %><br>
    <%= f.number_field :admin_id %>
  </div>
  <div class="field">
    <%= f.label :wallet_id %><br>
    <%= f.number_field :wallet_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ultra_reups/edit.html.erb
<h1>Editing ultra_reup</h1>

<%= render 'form' %>

<%= link_to 'Show', @ultra_reup %> |
<%= link_to 'Back', ultra_reups_path %>

app/views/ultra_reups/index.html.erb
<h1>Listing ultra_reups</h1>

<table>
  <thead>
    <tr>
      <th>Phone number</th>
      <th>Nineteen plan</th>
      <th>Twentynine plan</th>
      <th>Thirtynine plan</th>
      <th>Fourtynine plan</th>
      <th>Fiftynine plan</th>
      <th>Other amount</th>
      <th>Amount</th>
      <th>Admin</th>
      <th>Wallet</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @ultra_reups.each do |ultra_reup| %>
      <tr>
        <td><%= ultra_reup.phone_number %></td>
        <td><%= ultra_reup.nineteen_plan %></td>
        <td><%= ultra_reup.twentynine_plan %></td>
        <td><%= ultra_reup.thirtynine_plan %></td>
        <td><%= ultra_reup.fourtynine_plan %></td>
        <td><%= ultra_reup.fiftynine_plan %></td>
        <td><%= ultra_reup.other_amount %></td>
        <td><%= ultra_reup.amount %></td>
        <td><%= ultra_reup.admin_id %></td>
        <td><%= ultra_reup.wallet_id %></td>
        <td><%= link_to 'Show', ultra_reup %></td>
        <td><%= link_to 'Edit', edit_ultra_reup_path(ultra_reup) %></td>
        <td><%= link_to 'Destroy', ultra_reup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ultra reup', new_ultra_reup_path %>

app/views/ultra_reups/new.html.erb
<h1>New ultra_reup</h1>

<%= render 'form' %>

<%= link_to 'Back', ultra_reups_path %>

app/views/ultra_reups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Phone number:</strong>
  <%= @ultra_reup.phone_number %>
</p>

<p>
  <strong>Nineteen plan:</strong>
  <%= @ultra_reup.nineteen_plan %>
</p>

<p>
  <strong>Twentynine plan:</strong>
  <%= @ultra_reup.twentynine_plan %>
</p>

<p>
  <strong>Thirtynine plan:</strong>
  <%= @ultra_reup.thirtynine_plan %>
</p>

<p>
  <strong>Fourtynine plan:</strong>
  <%= @ultra_reup.fourtynine_plan %>
</p>

<p>
  <strong>Fiftynine plan:</strong>
  <%= @ultra_reup.fiftynine_plan %>
</p>

<p>
  <strong>Other amount:</strong>
  <%= @ultra_reup.other_amount %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @ultra_reup.amount %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @ultra_reup.admin_id %>
</p>

<p>
  <strong>Wallet:</strong>
  <%= @ultra_reup.wallet_id %>
</p>

<%= link_to 'Edit', edit_ultra_reup_path(@ultra_reup) %> |
<%= link_to 'Back', ultra_reups_path %>