config/routes.rb
Abc74st20::Application.routes.draw do
  root :to => "interface#dasboard"
  get "activations" => "interface#activations"

  get "portins" => "interface#portins"

  get "reups" => "interface#reups"
  resources :admins

  resources :reups

  resources :simple_portins

  resources :simple_activations

  resources :ultra_reups

  resources :ultra_portins

  resources :ultra_activations

  resources :wallets

  resources :ptel_reups

  resources :ptel_portins

  resources :ptel_activations

  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
	has_one :wallet
	has_many :ptel_activations, :through => :wallet
	has_many :ptel_portins, :through => :wallet
	has_many :ptel_reups, :through => :wallet 
	has_many :ultra_activations, :through => :wallet
	has_many :ultra_portins, :through => :wallet 
	has_many :ultra_reups, :through => :wallet
	has_many :simple_activations, :through => :wallet
	has_many :simple_portins, :through => :wallet 
	has_many :simple_reups, :through => :wallet
	has_many :lyca_activations, :through => :wallet 
	has_many :lyca_reups, :through => :wallet 
	has_many :lyca_portins, :through => :wallet
	has_many :tmobile_activations, :through => :wallet
	has_many :tmobile_portins, :through => :wallet
	has_many :tmobile_reups, :through => :wallet
	has_many :h20_activations, :through => :wallet
	has_many :h20_portins, :through => :wallet
	has_many :h20_reups, :through => :wallet 
	has_many :international_recharges, :through => :wallet  
	has_many :cellphone_unlockings, :through => :wallet        
end

app/models/ptel_activation.rb
class PtelActivation < ActiveRecord::Base
	belongs_to :admin
end

app/models/ptel_portin.rb
class PtelPortin < ActiveRecord::Base
	belongs_to :admin
end

app/models/ptel_reup.rb
class PtelReup < ActiveRecord::Base
	belongs_to :admin
end

app/models/reup.rb
class Reup < ActiveRecord::Base
	belongs_to :admin
	#this belongs to simple reup
end

app/models/simple_activation.rb
class SimpleActivation < ActiveRecord::Base
	belongs_to :admin
end

app/models/simple_portin.rb
class SimplePortin < ActiveRecord::Base
	belongs_to :admin
end

app/models/ultra_activation.rb
class UltraActivation < ActiveRecord::Base
	belongs_to :admin
end

app/models/ultra_portin.rb
class UltraPortin < ActiveRecord::Base
	belongs_to :admin
end

app/models/ultra_reup.rb
class UltraReup < ActiveRecord::Base
	belongs_to :admin
end

app/models/wallet.rb
class Wallet < ActiveRecord::Base
	belongs_to :admin
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :set_admin, only: [:show, :edit, :update, :destroy]

  # GET /admins
  # GET /admins.json
  def index
    @admins = Admin.all
  end

  # GET /admins/1
  # GET /admins/1.json
  def show
  end

  # GET /admins/new
  def new
    @admin = Admin.new
  end

  # GET /admins/1/edit
  def edit
  end

  # POST /admins
  # POST /admins.json
  def create
    @admin = Admin.new(admin_params)

    respond_to do |format|
      if @admin.save
        format.html { redirect_to @admin, notice: 'Admin was successfully created.' }
        format.json { render action: 'show', status: :created, location: @admin }
      else
        format.html { render action: 'new' }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admins/1
  # PATCH/PUT /admins/1.json
  def update
    respond_to do |format|
      if @admin.update(admin_params)
        format.html { redirect_to @admin, notice: 'Admin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admins/1
  # DELETE /admins/1.json
  def destroy
    @admin.destroy
    respond_to do |format|
      format.html { redirect_to admins_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin
      @admin = Admin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_params
      params.require(:admin).permit(:first_name, :last_name, :store_number, :cell_number, :address, :city, :state, :zip, :store_name, :email, :autorised_person)
    end
end

app/controllers/ptel_reups_controller.rb
class PtelReupsController < ApplicationController
  before_action :set_ptel_reup, only: [:show, :edit, :update, :destroy]

  # GET /ptel_reups
  # GET /ptel_reups.json
  def index
    @ptel_reups = PtelReup.all
  end

  # GET /ptel_reups/1
  # GET /ptel_reups/1.json
  def show
  end

  # GET /ptel_reups/new
  def new
    @ptel_reup = PtelReup.new
  end

  # GET /ptel_reups/1/edit
  def edit
  end

  # POST /ptel_reups
  # POST /ptel_reups.json
  def create
    @ptel_reup = PtelReup.new(ptel_reup_params)

    respond_to do |format|
      if @ptel_reup.save
        format.html { redirect_to @ptel_reup, notice: 'Ptel reup was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ptel_reup }
      else
        format.html { render action: 'new' }
        format.json { render json: @ptel_reup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ptel_reups/1
  # PATCH/PUT /ptel_reups/1.json
  def update
    respond_to do |format|
      if @ptel_reup.update(ptel_reup_params)
        format.html { redirect_to @ptel_reup, notice: 'Ptel reup was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ptel_reup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ptel_reups/1
  # DELETE /ptel_reups/1.json
  def destroy
    @ptel_reup.destroy
    respond_to do |format|
      format.html { redirect_to ptel_reups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ptel_reup
      @ptel_reup = PtelReup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ptel_reup_params
      params.require(:ptel_reup).permit(:pone_number, :fourty_plan, :fifty_plan, :real_paygo, :paygo_amount, :admin_id, :wallet_id)
    end
end

app/controllers/reups_controller.rb
class ReupsController < ApplicationController
  before_action :set_reup, only: [:show, :edit, :update, :destroy]
#this belongs to simple reup
  # GET /reups
  # GET /reups.json
  def index
    @reups = Reup.all
  end

  # GET /reups/1
  # GET /reups/1.json
  def show
  end

  # GET /reups/new
  def new
    @reup = Reup.new
  end

  # GET /reups/1/edit
  def edit
  end

  # POST /reups
  # POST /reups.json
  def create
    @reup = Reup.new(reup_params)

    respond_to do |format|
      if @reup.save
        format.html { redirect_to @reup, notice: 'Reup was successfully created.' }
        format.json { render action: 'show', status: :created, location: @reup }
      else
        format.html { render action: 'new' }
        format.json { render json: @reup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reups/1
  # PATCH/PUT /reups/1.json
  def update
    respond_to do |format|
      if @reup.update(reup_params)
        format.html { redirect_to @reup, notice: 'Reup was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @reup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reups/1
  # DELETE /reups/1.json
  def destroy
    @reup.destroy
    respond_to do |format|
      format.html { redirect_to reups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reup
      @reup = Reup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reup_params
      params.require(:reup).permit(:phone_number, :twentyfive_plan, :fourty_plan, :fifty_plan, :sixty_plan, :seventy_plan, :change_plan, :admin_id, :wallet_id)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interface_helper.rb
module InterfaceHelper
end

app/helpers/ptel_portins_helper.rb
module PtelPortinsHelper
end

app/helpers/ptel_reups_helper.rb
module PtelReupsHelper
end

app/helpers/reups_helper.rb
module ReupsHelper
end

app/helpers/ultra_portins_helper.rb
module UltraPortinsHelper
end

app/helpers/ultra_reups_helper.rb
module UltraReupsHelper
end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/views/ptel_reups/_form.html.erb
<%= form_for(@ptel_reup) do |f| %>
  <% if @ptel_reup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ptel_reup.errors.count, "error") %> prohibited this ptel_reup from being saved:</h2>

      <ul>
      <% @ptel_reup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pone_number %><br>
    <%= f.text_field :pone_number %>
  </div>
  <div class="field">
    <%= f.label :fourty_plan %><br>
    <%= f.check_box :fourty_plan %>
  </div>
  <div class="field">
    <%= f.label :fifty_plan %><br>
    <%= f.check_box :fifty_plan %>
  </div>
  <div class="field">
    <%= f.label :real_paygo %><br>
    <%= f.check_box :real_paygo %>
  </div>
  <div class="field">
    <%= f.label :paygo_amount %><br>
    <%= f.number_field :paygo_amount %>
  </div>
  <div class="field">
    <%= f.label :admin_id %><br>
    <%= f.number_field :admin_id %>
  </div>
  <div class="field">
    <%= f.label :wallet_id %><br>
    <%= f.number_field :wallet_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ptel_reups/edit.html.erb
<h1>Editing ptel_reup</h1>

<%= render 'form' %>

<%= link_to 'Show', @ptel_reup %> |
<%= link_to 'Back', ptel_reups_path %>

app/views/ptel_reups/index.html.erb
<h1>Listing ptel_reups</h1>

<table>
  <thead>
    <tr>
      <th>Pone number</th>
      <th>Fourty plan</th>
      <th>Fifty plan</th>
      <th>Real paygo</th>
      <th>Paygo amount</th>
      <th>Admin</th>
      <th>Wallet</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @ptel_reups.each do |ptel_reup| %>
      <tr>
        <td><%= ptel_reup.pone_number %></td>
        <td><%= ptel_reup.fourty_plan %></td>
        <td><%= ptel_reup.fifty_plan %></td>
        <td><%= ptel_reup.real_paygo %></td>
        <td><%= ptel_reup.paygo_amount %></td>
        <td><%= ptel_reup.admin_id %></td>
        <td><%= ptel_reup.wallet_id %></td>
        <td><%= link_to 'Show', ptel_reup %></td>
        <td><%= link_to 'Edit', edit_ptel_reup_path(ptel_reup) %></td>
        <td><%= link_to 'Destroy', ptel_reup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ptel reup', new_ptel_reup_path %>

app/views/ptel_reups/new.html.erb
<h1>New ptel_reup</h1>

<%= render 'form' %>

<%= link_to 'Back', ptel_reups_path %>

app/views/ptel_reups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pone number:</strong>
  <%= @ptel_reup.pone_number %>
</p>

<p>
  <strong>Fourty plan:</strong>
  <%= @ptel_reup.fourty_plan %>
</p>

<p>
  <strong>Fifty plan:</strong>
  <%= @ptel_reup.fifty_plan %>
</p>

<p>
  <strong>Real paygo:</strong>
  <%= @ptel_reup.real_paygo %>
</p>

<p>
  <strong>Paygo amount:</strong>
  <%= @ptel_reup.paygo_amount %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @ptel_reup.admin_id %>
</p>

<p>
  <strong>Wallet:</strong>
  <%= @ptel_reup.wallet_id %>
</p>

<%= link_to 'Edit', edit_ptel_reup_path(@ptel_reup) %> |
<%= link_to 'Back', ptel_reups_path %>