config/routes.rb
Abc74st20::Application.routes.draw do
  root :to => "interface#dasboard"
  get "activations" => "interface#activations"

  get "portins" => "interface#portins"

  get "reups" => "interface#reups"
  resources :admins

  resources :reups

  resources :simple_portins

  resources :simple_activations

  resources :ultra_reups

  resources :ultra_portins

  resources :ultra_activations

  resources :wallets

  resources :ptel_reups

  resources :ptel_portins

  resources :ptel_activations

  

end

app/models/ptel_portin.rb
class PtelPortin < ActiveRecord::Base
	belongs_to :admin
end

app/controllers/ptel_portins_controller.rb
class PtelPortinsController < ApplicationController
  before_action :set_ptel_portin, only: [:show, :edit, :update, :destroy]

  # GET /ptel_portins
  # GET /ptel_portins.json
  def index
    @ptel_portins = PtelPortin.all
  end

  # GET /ptel_portins/1
  # GET /ptel_portins/1.json
  def show
  end

  # GET /ptel_portins/new
  def new
    @ptel_portin = PtelPortin.new
  end

  # GET /ptel_portins/1/edit
  def edit
  end

  # POST /ptel_portins
  # POST /ptel_portins.json
  def create
    @ptel_portin = PtelPortin.new(ptel_portin_params)

    respond_to do |format|
      if @ptel_portin.save
        format.html { redirect_to @ptel_portin, notice: 'Ptel portin was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ptel_portin }
      else
        format.html { render action: 'new' }
        format.json { render json: @ptel_portin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ptel_portins/1
  # PATCH/PUT /ptel_portins/1.json
  def update
    respond_to do |format|
      if @ptel_portin.update(ptel_portin_params)
        format.html { redirect_to @ptel_portin, notice: 'Ptel portin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ptel_portin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ptel_portins/1
  # DELETE /ptel_portins/1.json
  def destroy
    @ptel_portin.destroy
    respond_to do |format|
      format.html { redirect_to ptel_portins_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ptel_portin
      @ptel_portin = PtelPortin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ptel_portin_params
      params.require(:ptel_portin).permit(:existing_number, :first_name, :last_name, :contact_number, :address, :city, :state, :zip_code, :email, :old_service_provider, :old_account_id, :old_account_password, :fourtyplan, :fiftyplan, :real_paygo, :paygo_amount, :comments, :wallet_id, :admin_id)
    end
end

app/helpers/ptel_portins_helper.rb
module PtelPortinsHelper
end

app/views/ptel_portins/_form.html.erb
<%= form_for(@ptel_portin) do |f| %>
  <% if @ptel_portin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ptel_portin.errors.count, "error") %> prohibited this ptel_portin from being saved:</h2>

      <ul>
      <% @ptel_portin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :existing_number %><br>
    <%= f.text_field :existing_number %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :contact_number %><br>
    <%= f.text_field :contact_number %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip_code %><br>
    <%= f.text_field :zip_code %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :old_service_provider %><br>
    <%= f.text_field :old_service_provider %>
  </div>
  <div class="field">
    <%= f.label :old_account_id %><br>
    <%= f.text_field :old_account_id %>
  </div>
  <div class="field">
    <%= f.label :old_account_password %><br>
    <%= f.text_field :old_account_password %>
  </div>
  <div class="field">
    <%= f.label :fourtyplan %><br>
    <%= f.check_box :fourtyplan %>
  </div>
  <div class="field">
    <%= f.label :fiftyplan %><br>
    <%= f.check_box :fiftyplan %>
  </div>
  <div class="field">
    <%= f.label :real_paygo %><br>
    <%= f.check_box :real_paygo %>
  </div>
  <div class="field">
    <%= f.label :paygo_amount %><br>
    <%= f.number_field :paygo_amount %>
  </div>
  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_area :comments %>
  </div>
  <div class="field">
    <%= f.label :wallet_id %><br>
    <%= f.number_field :wallet_id %>
  </div>
  <div class="field">
    <%= f.label :admin_id %><br>
    <%= f.number_field :admin_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ptel_portins/edit.html.erb
<h1>Editing ptel_portin</h1>

<%= render 'form' %>

<%= link_to 'Show', @ptel_portin %> |
<%= link_to 'Back', ptel_portins_path %>

app/views/ptel_portins/index.html.erb
<h1>Listing ptel_portins</h1>

<table>
  <thead>
    <tr>
      <th>Existing number</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Contact number</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip code</th>
      <th>Email</th>
      <th>Old service provider</th>
      <th>Old account</th>
      <th>Old account password</th>
      <th>Fourtyplan</th>
      <th>Fiftyplan</th>
      <th>Real paygo</th>
      <th>Paygo amount</th>
      <th>Comments</th>
      <th>Wallet</th>
      <th>Admin</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @ptel_portins.each do |ptel_portin| %>
      <tr>
        <td><%= ptel_portin.existing_number %></td>
        <td><%= ptel_portin.first_name %></td>
        <td><%= ptel_portin.last_name %></td>
        <td><%= ptel_portin.contact_number %></td>
        <td><%= ptel_portin.address %></td>
        <td><%= ptel_portin.city %></td>
        <td><%= ptel_portin.state %></td>
        <td><%= ptel_portin.zip_code %></td>
        <td><%= ptel_portin.email %></td>
        <td><%= ptel_portin.old_service_provider %></td>
        <td><%= ptel_portin.old_account_id %></td>
        <td><%= ptel_portin.old_account_password %></td>
        <td><%= ptel_portin.fourtyplan %></td>
        <td><%= ptel_portin.fiftyplan %></td>
        <td><%= ptel_portin.real_paygo %></td>
        <td><%= ptel_portin.paygo_amount %></td>
        <td><%= ptel_portin.comments %></td>
        <td><%= ptel_portin.wallet_id %></td>
        <td><%= ptel_portin.admin_id %></td>
        <td><%= link_to 'Show', ptel_portin %></td>
        <td><%= link_to 'Edit', edit_ptel_portin_path(ptel_portin) %></td>
        <td><%= link_to 'Destroy', ptel_portin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ptel portin', new_ptel_portin_path %>

app/views/ptel_portins/new.html.erb
<h1>New ptel_portin</h1>

<%= render 'form' %>

<%= link_to 'Back', ptel_portins_path %>

app/views/ptel_portins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Existing number:</strong>
  <%= @ptel_portin.existing_number %>
</p>

<p>
  <strong>First name:</strong>
  <%= @ptel_portin.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @ptel_portin.last_name %>
</p>

<p>
  <strong>Contact number:</strong>
  <%= @ptel_portin.contact_number %>
</p>

<p>
  <strong>Address:</strong>
  <%= @ptel_portin.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @ptel_portin.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @ptel_portin.state %>
</p>

<p>
  <strong>Zip code:</strong>
  <%= @ptel_portin.zip_code %>
</p>

<p>
  <strong>Email:</strong>
  <%= @ptel_portin.email %>
</p>

<p>
  <strong>Old service provider:</strong>
  <%= @ptel_portin.old_service_provider %>
</p>

<p>
  <strong>Old account:</strong>
  <%= @ptel_portin.old_account_id %>
</p>

<p>
  <strong>Old account password:</strong>
  <%= @ptel_portin.old_account_password %>
</p>

<p>
  <strong>Fourtyplan:</strong>
  <%= @ptel_portin.fourtyplan %>
</p>

<p>
  <strong>Fiftyplan:</strong>
  <%= @ptel_portin.fiftyplan %>
</p>

<p>
  <strong>Real paygo:</strong>
  <%= @ptel_portin.real_paygo %>
</p>

<p>
  <strong>Paygo amount:</strong>
  <%= @ptel_portin.paygo_amount %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @ptel_portin.comments %>
</p>

<p>
  <strong>Wallet:</strong>
  <%= @ptel_portin.wallet_id %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @ptel_portin.admin_id %>
</p>

<%= link_to 'Edit', edit_ptel_portin_path(@ptel_portin) %> |
<%= link_to 'Back', ptel_portins_path %>