config/routes.rb
Abc74st20::Application.routes.draw do
  root :to => "interface#dasboard"
  get "activations" => "interface#activations"

  get "portins" => "interface#portins"

  get "reups" => "interface#reups"
  resources :admins

  resources :reups

  resources :simple_portins

  resources :simple_activations

  resources :ultra_reups

  resources :ultra_portins

  resources :ultra_activations

  resources :wallets

  resources :ptel_reups

  resources :ptel_portins

  resources :ptel_activations

  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
	has_one :wallet
	has_many :ptel_activations, :through => :wallet
	has_many :ptel_portins, :through => :wallet
	has_many :ptel_reups, :through => :wallet 
	has_many :ultra_activations, :through => :wallet
	has_many :ultra_portins, :through => :wallet 
	has_many :ultra_reups, :through => :wallet
	has_many :simple_activations, :through => :wallet
	has_many :simple_portins, :through => :wallet 
	has_many :simple_reups, :through => :wallet
	has_many :lyca_activations, :through => :wallet 
	has_many :lyca_reups, :through => :wallet 
	has_many :lyca_portins, :through => :wallet
	has_many :tmobile_activations, :through => :wallet
	has_many :tmobile_portins, :through => :wallet
	has_many :tmobile_reups, :through => :wallet
	has_many :h20_activations, :through => :wallet
	has_many :h20_portins, :through => :wallet
	has_many :h20_reups, :through => :wallet 
	has_many :international_recharges, :through => :wallet  
	has_many :cellphone_unlockings, :through => :wallet        
end

app/models/ptel_activation.rb
class PtelActivation < ActiveRecord::Base
	belongs_to :admin
end

app/models/ptel_portin.rb
class PtelPortin < ActiveRecord::Base
	belongs_to :admin
end

app/models/ptel_reup.rb
class PtelReup < ActiveRecord::Base
	belongs_to :admin
end

app/models/reup.rb
class Reup < ActiveRecord::Base
	belongs_to :admin
	#this belongs to simple reup
end

app/models/simple_activation.rb
class SimpleActivation < ActiveRecord::Base
	belongs_to :admin
end

app/models/simple_portin.rb
class SimplePortin < ActiveRecord::Base
	belongs_to :admin
end

app/models/ultra_activation.rb
class UltraActivation < ActiveRecord::Base
	belongs_to :admin
end

app/models/ultra_portin.rb
class UltraPortin < ActiveRecord::Base
	belongs_to :admin
end

app/models/ultra_reup.rb
class UltraReup < ActiveRecord::Base
	belongs_to :admin
end

app/models/wallet.rb
class Wallet < ActiveRecord::Base
	belongs_to :admin
end

app/controllers/reups_controller.rb
class ReupsController < ApplicationController
  before_action :set_reup, only: [:show, :edit, :update, :destroy]
#this belongs to simple reup
  # GET /reups
  # GET /reups.json
  def index
    @reups = Reup.all
  end

  # GET /reups/1
  # GET /reups/1.json
  def show
  end

  # GET /reups/new
  def new
    @reup = Reup.new
  end

  # GET /reups/1/edit
  def edit
  end

  # POST /reups
  # POST /reups.json
  def create
    @reup = Reup.new(reup_params)

    respond_to do |format|
      if @reup.save
        format.html { redirect_to @reup, notice: 'Reup was successfully created.' }
        format.json { render action: 'show', status: :created, location: @reup }
      else
        format.html { render action: 'new' }
        format.json { render json: @reup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reups/1
  # PATCH/PUT /reups/1.json
  def update
    respond_to do |format|
      if @reup.update(reup_params)
        format.html { redirect_to @reup, notice: 'Reup was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @reup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reups/1
  # DELETE /reups/1.json
  def destroy
    @reup.destroy
    respond_to do |format|
      format.html { redirect_to reups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reup
      @reup = Reup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reup_params
      params.require(:reup).permit(:phone_number, :twentyfive_plan, :fourty_plan, :fifty_plan, :sixty_plan, :seventy_plan, :change_plan, :admin_id, :wallet_id)
    end
end

app/controllers/simple_activations_controller.rb
class SimpleActivationsController < ApplicationController
  before_action :set_simple_activation, only: [:show, :edit, :update, :destroy]

  # GET /simple_activations
  # GET /simple_activations.json
  def index
    @simple_activations = SimpleActivation.all
  end

  # GET /simple_activations/1
  # GET /simple_activations/1.json
  def show
  end

  # GET /simple_activations/new
  def new
    @simple_activation = SimpleActivation.new
  end

  # GET /simple_activations/1/edit
  def edit
  end

  # POST /simple_activations
  # POST /simple_activations.json
  def create
    @simple_activation = SimpleActivation.new(simple_activation_params)

    respond_to do |format|
      if @simple_activation.save
        format.html { redirect_to @simple_activation, notice: 'Simple activation was successfully created.' }
        format.json { render action: 'show', status: :created, location: @simple_activation }
      else
        format.html { render action: 'new' }
        format.json { render json: @simple_activation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /simple_activations/1
  # PATCH/PUT /simple_activations/1.json
  def update
    respond_to do |format|
      if @simple_activation.update(simple_activation_params)
        format.html { redirect_to @simple_activation, notice: 'Simple activation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @simple_activation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /simple_activations/1
  # DELETE /simple_activations/1.json
  def destroy
    @simple_activation.destroy
    respond_to do |format|
      format.html { redirect_to simple_activations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_simple_activation
      @simple_activation = SimpleActivation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def simple_activation_params
      params.require(:simple_activation).permit(:sim_number, :zip_code, :twentyfive_plan, :fourty_plan, :fifty_plan, :sixty_plan, :ild, :admin_id, :wallet_id)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interface_helper.rb
module InterfaceHelper
end

app/helpers/ptel_portins_helper.rb
module PtelPortinsHelper
end

app/helpers/ptel_reups_helper.rb
module PtelReupsHelper
end

app/helpers/reups_helper.rb
module ReupsHelper
end

app/helpers/simple_activations_helper.rb
module SimpleActivationsHelper
end

app/helpers/ultra_portins_helper.rb
module UltraPortinsHelper
end

app/helpers/ultra_reups_helper.rb
module UltraReupsHelper
end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/views/simple_activations/_form.html.erb
<%= form_for(@simple_activation) do |f| %>
  <% if @simple_activation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@simple_activation.errors.count, "error") %> prohibited this simple_activation from being saved:</h2>

      <ul>
      <% @simple_activation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sim_number %><br>
    <%= f.text_field :sim_number %>
  </div>
  <div class="field">
    <%= f.label :zip_code %><br>
    <%= f.text_field :zip_code %>
  </div>
  <div class="field">
    <%= f.label :twentyfive_plan %><br>
    <%= f.check_box :twentyfive_plan %>
  </div>
  <div class="field">
    <%= f.label :fourty_plan %><br>
    <%= f.check_box :fourty_plan %>
  </div>
  <div class="field">
    <%= f.label :fifty_plan %><br>
    <%= f.check_box :fifty_plan %>
  </div>
  <div class="field">
    <%= f.label :sixty_plan %><br>
    <%= f.check_box :sixty_plan %>
  </div>
  <div class="field">
    <%= f.label :ild %><br>
    <%= f.check_box :ild %>
  </div>
  <div class="field">
    <%= f.label :admin_id %><br>
    <%= f.number_field :admin_id %>
  </div>
  <div class="field">
    <%= f.label :wallet_id %><br>
    <%= f.number_field :wallet_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/simple_activations/edit.html.erb
<h1>Editing simple_activation</h1>

<%= render 'form' %>

<%= link_to 'Show', @simple_activation %> |
<%= link_to 'Back', simple_activations_path %>

app/views/simple_activations/index.html.erb
<h1>Listing simple_activations</h1>

<table>
  <thead>
    <tr>
      <th>Sim number</th>
      <th>Zip code</th>
      <th>Twentyfive plan</th>
      <th>Fourty plan</th>
      <th>Fifty plan</th>
      <th>Sixty plan</th>
      <th>Ild</th>
      <th>Admin</th>
      <th>Wallet</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @simple_activations.each do |simple_activation| %>
      <tr>
        <td><%= simple_activation.sim_number %></td>
        <td><%= simple_activation.zip_code %></td>
        <td><%= simple_activation.twentyfive_plan %></td>
        <td><%= simple_activation.fourty_plan %></td>
        <td><%= simple_activation.fifty_plan %></td>
        <td><%= simple_activation.sixty_plan %></td>
        <td><%= simple_activation.ild %></td>
        <td><%= simple_activation.admin_id %></td>
        <td><%= simple_activation.wallet_id %></td>
        <td><%= link_to 'Show', simple_activation %></td>
        <td><%= link_to 'Edit', edit_simple_activation_path(simple_activation) %></td>
        <td><%= link_to 'Destroy', simple_activation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Simple activation', new_simple_activation_path %>

app/views/simple_activations/new.html.erb
<h1>New simple_activation</h1>

<%= render 'form' %>

<%= link_to 'Back', simple_activations_path %>

app/views/simple_activations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sim number:</strong>
  <%= @simple_activation.sim_number %>
</p>

<p>
  <strong>Zip code:</strong>
  <%= @simple_activation.zip_code %>
</p>

<p>
  <strong>Twentyfive plan:</strong>
  <%= @simple_activation.twentyfive_plan %>
</p>

<p>
  <strong>Fourty plan:</strong>
  <%= @simple_activation.fourty_plan %>
</p>

<p>
  <strong>Fifty plan:</strong>
  <%= @simple_activation.fifty_plan %>
</p>

<p>
  <strong>Sixty plan:</strong>
  <%= @simple_activation.sixty_plan %>
</p>

<p>
  <strong>Ild:</strong>
  <%= @simple_activation.ild %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @simple_activation.admin_id %>
</p>

<p>
  <strong>Wallet:</strong>
  <%= @simple_activation.wallet_id %>
</p>

<%= link_to 'Edit', edit_simple_activation_path(@simple_activation) %> |
<%= link_to 'Back', simple_activations_path %>